name: CI

on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      # 检查缓存
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: | 
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock')}}
      # 安装依赖
      - name: Install Dependence
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install
      # 执行任务
      - name: execute jobs
        run: npm run hello
      # 生成 release draft
      - name: Draft
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 发布 release
      - name: publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}