name: CI

on:
  pull_request:
    types: [closed]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      # 生成 release draft
      - name: Draft
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 发布 release
      - name: publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
      - name: publish to npm
        run: npm publish