# 打tag + release + 发布npm
name: Relase-Npm

on: pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      # 生成 release draft
      - name: Draft
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      # 发布 release
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
      - name: Publish To Npm
        uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{ secrets.NPM_TOKEN }}