name: Release Drafter

on:
  push:
    branches: main

jobs:
  Drafter:
    runs-on: ubuntu-latest
    steps:
      - name: build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft 
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
